const { COMPOSITE_FILE_FOLDER, COMPOSITE_FILENAME_PREFIX, COMPOSITE_FILE_EXTENSION } = process.env;

const COMPOSITE_FILE = {
  FOLDER: COMPOSITE_FILE_FOLDER,
  FILENAME_PREFIX: COMPOSITE_FILENAME_PREFIX,
  FILE_EXTENSION: COMPOSITE_FILE_EXTENSION,
};

module.exports = {
  COMPOSITE_FILE,
};
