service: movile-mlb-wellness-bot-image-generator
#app: image-generator
#org: luanapp

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: sa-east-1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
      - "s3:ListBucket"
    Resource: "arn:aws:s3:::mlb-movile/bot/*"

functions:
  image-generator:
    handler: src/handler.generate
    events:
      - http:
          path: image/generate
          method: get
    environment:
      AWS_S3_BUCKET: mlb-movile
      PLANTS_FOLDER: bot/plants/
      STANDS_FOLDER: bot/stand/
      BASE_FILE_FOLDER: bot/base
      BASE_FILENAME: garden-base.png

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
